#!/bin/sh
#
#  Sets CLASSPATH and runs whatever class - put it
#  as the first argument. Use this script until you create
#  a specialized script for your application.
#
#  $Id: run-any-client,v 1.5 2007/06/19 21:39:26 marsenger Exp $
# ----------------------------------------------------

PROJECT_HOME=@PROJECT_HOME@
LIBS_PATH=@PROJECT_DEPS@

CLASSPATH=$LIBS_PATH
CLASSPATH=`echo ${PROJECT_HOME}/build/lib/*.jar | tr ' ' ':'`:$CLASSPATH
CLASSPATH=${PROJECT_HOME}/build/classes:$CLASSPATH
CLASSPATH=${PROJECT_HOME}/build/plugins:$CLASSPATH

exec java -cp $CLASSPATH @LOG4J@ "$@"
