#!/usr/bin/perl -w
#
# It prints all its command-line to STDOUT.
#
# This is a simple UNIX 'echo' program - and it is here
# because of running Soaplab2 under Windows.
#
# $Id: echo,v 1.1 2007/10/23 14:06:57 marsenger Exp $
# ---------------------------------------------

use strict;
use warnings;

print join (" ", @ARGV), "\n";
