//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.27 at 03:28:05 PM BST 
//


package org.soaplab.typedws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.soaplab.typedws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.soaplab.typedws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Terminate }
     * 
     */
    public Terminate createTerminate() {
        return new Terminate();
    }

    /**
     * Create an instance of {@link Clear }
     * 
     */
    public Clear createClear() {
        return new Clear();
    }

    /**
     * Create an instance of {@link GetStatus }
     * 
     */
    public GetStatus createGetStatus() {
        return new GetStatus();
    }

    /**
     * Create an instance of {@link ResultInfo }
     * 
     */
    public ResultInfo createResultInfo() {
        return new ResultInfo();
    }

    /**
     * Create an instance of {@link GetResultsInfoResponse }
     * 
     */
    public GetResultsInfoResponse createGetResultsInfoResponse() {
        return new GetResultsInfoResponse();
    }

    /**
     * Create an instance of {@link GetResults }
     * 
     */
    public GetResults createGetResults() {
        return new GetResults();
    }

    /**
     * Create an instance of {@link DescribeResponse }
     * 
     */
    public DescribeResponse createDescribeResponse() {
        return new DescribeResponse();
    }

    /**
     * Create an instance of {@link GetStatusResponse }
     * 
     */
    public GetStatusResponse createGetStatusResponse() {
        return new GetStatusResponse();
    }

    /**
     * Create an instance of {@link Describe }
     * 
     */
    public Describe createDescribe() {
        return new Describe();
    }

    /**
     * Create an instance of {@link Waitfor }
     * 
     */
    public Waitfor createWaitfor() {
        return new Waitfor();
    }

    /**
     * Create an instance of {@link JobId }
     * 
     */
    public JobId createJobId() {
        return new JobId();
    }

    /**
     * Create an instance of {@link GetSomeResults }
     * 
     */
    public GetSomeResults createGetSomeResults() {
        return new GetSomeResults();
    }

    /**
     * Create an instance of {@link RunResponse }
     * 
     */
    public RunResponse createRunResponse() {
        return new RunResponse();
    }

    /**
     * Create an instance of {@link GetLastEvent }
     * 
     */
    public GetLastEvent createGetLastEvent() {
        return new GetLastEvent();
    }

    /**
     * Create an instance of {@link GetLastEventResponse }
     * 
     */
    public GetLastEventResponse createGetLastEventResponse() {
        return new GetLastEventResponse();
    }

    /**
     * Create an instance of {@link GetResultsInfo }
     * 
     */
    public GetResultsInfo createGetResultsInfo() {
        return new GetResultsInfo();
    }

}
